#coding=utf-8
from django.conf.urls.defaults import patterns

urlpatterns = patterns('main.views.receptionist',
    (r'^registerList/$', 'register_list'),
    (r'^checkInCancell/(?P<appointment_id>\d+)/$', 'check_in_cancell'),
    (r'^checkIn/(?P<appointment_id>\d+)/$', 'check_in'),
    (r'^checkInConfirm/(?P<appointment_id>\d+)/$', 'check_in_confirm'),
    (r'^checkOut/(?P<appointment_id>\d+)/$', 'check_out'),
    (r'^cancel/(?P<appointment_id>\d+)/$', 'cancel'),
    (r'^cancelSchedule/(?P<schedule_id>\d+)/(?P<month>\d+)/$', 'cancel_schedule'),
    (r'^scheduleList/(?P<month>-?\d+)/$', 'schedule_list_view'),
    (r'^amendTimesolt/(?P<month>-?\d+)/$', 'amend_timesolt'),
    (r'^addTimesolts/(?P<year>-?\d+)/(?P<month>-?\d+)/(?P<day>-?\d+)/$', 'add_timesolt'),
    (r'^patients/$', 'patients_view'),
    (r'^rescheduleList2/(?P<appointment_id>\d+)/$', 'reschedule_list_view2'),
    (r'^reschedule2/(?P<appointment_id>\d+)/$', 'reschedule_view2'),
    (r'^rescheduleAction2/(?P<schedule_id>\d+)/(?P<appointment_id>\d+)/$', 'reschedule_action2'),
    (r'^rescheduleList/(?P<appointment_id>\d+)/$', 'reschedule_list_view'),
    (r'^reschedule/(?P<appointment_id>\d+)/$', 'reschedule_view'),
    (r'^rescheduleAction/(?P<schedule_id>\d+)/(?P<appointment_id>\d+)/$', 'reschedule_action'),
    (r'^logs/$', 'logs'),
    (r'^registerCancellation/(?P<appointment_id>\d+)/$', 'cancel_register'),
    (r'^registered_view/(?P<appointment_id>\d+)/$', 'register_cancellation_view'),
)